# Generated by Django 2.2.5 on 2020-01-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=15, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, default=None, null=True, verbose_name='Date of birth')),
            ],
            options={
                'verbose_name': 'Astronaut',
                'verbose_name_plural': 'Astronauts',
            },
        ),
    ]
