# Generated by Django 2.2.5 on 2020-01-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
